### PR TITLE
VTCCA-5796 - Add new listYears field to getMyOrganisationAgents call

### PR DESCRIPTION
**Pull request by kabuumu**

### CODE REVIEW

**Comment by zachhall1234** [comment]
LGTM 👍

**Comment by PeterPerhac** [comment]
👍 looks good. Thanks for setting this up.

**Comment by zachhall1234** [comment]
We probably need to update precommit alias to include the it:test.

Potentially in build-jobs too

**Comment by MarkAKelly** [comment]
In the requirements we've got the addition of a feature switch to toggle whether the optional data is required:

>  On frontend, if feature switch is enabled then will throw exception if field is not present.

Is that meant to be added as part of this change or another time?

**Pull request merged**
