### PR TITLE
VTCCA-4451: fix

### PR DESCRIPTION
**Pull request by zahiriqbal**

### CODE REVIEW

**Comment by habeeb01** [comment]
LGTM 👍

**Comment by reddy-yattapu** [comment]
:+1:

**Comment by PeterPerhac** [comment]
Can you update the PR title to give more detail than just "fix" ?

**Comment by PeterPerhac** [comment]
Also I noticed one of the commits doesn't have a ticket reference. can you make sure you have run the setup-githook script in ALL your repositories?

**Pull request merged**
