### PR TITLE
VTCCA-5168 fix manual address link not showing, fix bugs resulting from fix, refactor address partial DI

### PR DESCRIPTION
**Pull request by DanSmith98**

### CODE REVIEW

**Comment by habeeb01** [comment]
Dan to add a test to check that the "Enter address manually" link is displayed on load of the page

**Comment by DanSmith98** [comment]
I've added some testing on the visibility of the manual entry link. It's not as comprehensive as I'd like, partially because of the javascript and partially because I can't run the 'update address' screens locally. I'll add a comment on the ticket to regression test those pages as well.

**Comment by reddy-yattapu** [comment]
👍

**Comment by habeeb01** [comment]
LGTM 👍

**Pull request merged**
