### PR TITLE
VTCCA-4785 add new link to Appoint an agent to Manage Agents

### PR DESCRIPTION
**Pull request by PeterPerhac**
note, I didn't post a JIRA link

### CODE REVIEW

**Comment by darrell-plant** [comment]
LGTDz 👍

**Comment by darrell-plant** [comment]
@PeterPerhac someone suggested you add a unit test...

**Comment by PeterPerhac** [comment]
> @PeterPerhac someone suggested you add a unit test...

I did. Add the unit test.

**Comment by habeeb01** [comment]
LGTM 👍

**Pull request merged**
