### PR TITLE
VTCCA-3224 rebasing with master

### PR DESCRIPTION
**Pull request by DanielConnelly**

### CODE REVIEW

**Comment by darrell-plant** [comment]
lgtm 👍

**Comment by habeeb01** [comment]
👍

**Comment by PeterPerhac** [comment]
don't know what this PR is about... "rebasing with master"

**Comment by DanielConnelly** [comment]
> don't know what this PR is about... "rebasing with master"
 
I named PR wrong. this is about VTCCA-3224 (making effective dates clickable links)

**Pull request merged**
